Ds 179 picture hash
kb-dk/ds-image-analysis-old pull request #1
Opened 2020-01-13 13:30 UTC by Knud-Aage

Initial version of a webservice that gives a hash value of a picture

2020-01-15 10:34 UTC, tokee requested changes
The service has separate calls for the separate functions (`imageDHash`, `imagePHash`, `imageCHash`). While this is easy to understand & use, it also means a lot of calls as an indexing service will call all the methods after each other. If this structure is to be used, then the service should cache recently retrieved images, to avoid overloading the image server. Alternatively (may favourite), there should be a single `analyze`-call, where it is possible to provide a list of the calculations to perform: `http://.../analyze?methods=dhash,phash?imgURL=...`.

2020-01-15 10:47 UTC, tokee requested changes

2020-01-15 10:47 UTC, tokee commented on ds-pictureHash-swagger/src/main/swagger/ds-pictureHash.yml
> +        - name: imgPath
This should be imgURL

2020-01-15 10:47 UTC, tokee commented on ds-pictureHash-swagger/src/main/swagger/ds-pictureHash.yml
> +  /imageDHash/imgPath:
It seems redundant to have `imgPath` here when it is also a parameter?

2020-01-15 10:47 UTC, tokee commented on README.md
> +
Could you add a note about building & running the service?

2020-01-15 10:47 UTC, tokee commented on conf/localtomcat9/ds-pictureHash.xml
> +        value="${user.home}/Code/Repository/Digitale_Samlinger/ds-pictureHash/conf/localtomcat9_halh/logback.xml"
This is a local path. Should the `localtomcat9`-folder be in the repository at all?

2020-01-15 10:47 UTC, tokee commented on ds-pictureHash-swagger/src/main/swagger/ds-pictureHash.yml
> +          description: Hash value from the API
Please describe how the hash value looks (hex/int/binary/string? length?). Ideally provide an example.

2020-01-15 10:47 UTC, tokee commented on ds-pictureHash-swagger/src/main/swagger/ds-pictureHash.yml
> +      summary: 'Request imageDPHash from an image at the Royal Danish Library'
Please describe what a DPHash is or provide a link to a webpage with that description

2020-01-15 10:47 UTC, tokee commented on ds-pictureHash-ws/src/main/java/dk/kb/api/webservice/ApiServiceImpl.java
> +    public HashReplyDto getImageDHash(String imgPath) {
There does not seem to be any test methods for any of the methods? Please provide at least one.

2020-01-24 09:11 UTC, Knud-Aage commented on ds-pictureHash-ws/src/main/java/dk/kb/api/webservice/ApiServiceImpl.java
> +    public HashReplyDto getImageDHash(String imgPath) {
Test methods added

2020-01-24 09:11 UTC, Knud-Aage commented on ds-pictureHash-swagger/src/main/swagger/ds-pictureHash.yml
> +      summary: 'Request imageDPHash from an image at the Royal Danish Library'
Oops, it is now changed to DHash

2020-01-24 09:11 UTC, Knud-Aage commented on ds-pictureHash-swagger/src/main/swagger/ds-pictureHash.yml
> +          description: Hash value from the API
The format of the hash value is added - it is a BigInteger that is returned.

2020-01-24 09:11 UTC, Knud-Aage commented on conf/localtomcat9/ds-pictureHash.xml
> +        value="${user.home}/Code/Repository/Digitale_Samlinger/ds-pictureHash/conf/localtomcat9_halh/logback.xml"
The file is now removed from the project

2020-01-24 09:11 UTC, Knud-Aage commented on README.md
> +
Explanation is now added to the README.md

2020-01-24 09:12 UTC, Knud-Aage commented on ds-pictureHash-swagger/src/main/swagger/ds-pictureHash.yml
> +  /imageDHash/imgPath:
It apparently is the way that is possible with swagger

2020-01-24 09:12 UTC, Knud-Aage commented on ds-pictureHash-swagger/src/main/swagger/ds-pictureHash.yml
> +        - name: imgPath
Done

2020-01-27 09:56 UTC, merged