Digisam 212 hash precision
kb-dk/ds-image-analysis-old pull request #2
Opened 2020-01-31 10:14 UTC by Knud-Aage

Introduce DHash and PHash with multiple different size hash values, so it is possible to give same hash value to similar pictures.
Furthermore a calculation of the distance between two hash values

2020-01-31 12:59 UTC, tokee requested changes
The unit-tests uses calls to the image server. This is not ideal. Please put some (small and highly compresses JPEG) images in the test-resources folder and use them instead.

Some of the unit-tests do not run. There seems to be a problem with the Maven setup so that it does not run unit-tests at all. I am discussing this with @sbktc - in the mean time you can run the unit-tests from IDEA.

2020-01-31 12:59 UTC, tokee commented on ds-image-analysis-ws/src/main/java/dk/kb/api/webservice/ApiServiceImpl.java
> +    private static final String filePath= "imgHash";
This should be a unique file, preferably in the system's `tmp`-folder. The method `Files.createTempFile` does exactly this.

2020-01-31 12:59 UTC, tokee commented on ds-image-analysis-ws/src/main/java/dk/kb/api/webservice/ApiServiceImpl.java
> +            Files.deleteIfExists(Paths.get(filePath));
Clean up should be done even if the code above throws an Exception. Please move this line outside of the `try`-block.

2020-01-31 13:24 UTC, tokee requested changes

2020-01-31 13:24 UTC, tokee commented on ds-image-analysis-ws/src/test/java/dk/kb/api/webservice/ApiServiceImplTest.java
> +        Assertions.assertEquals(true, result.contains("message: 2"));
`assertEquals(true, <something>)` can be replaced with `assertTrue(<something>)`, which is easier to read and more precise.

2020-01-31 13:24 UTC, tokee commented on ds-image-analysis-ws/src/main/java/dk/kb/api/webservice/ApiServiceImpl.java
> +            hashValue(replyBuilder,imgHash, DifferenceHash.Precision.Triple);
So the precision is part of the DifferenceHash-implementation. Nice!

2020-01-31 13:24 UTC, tokee commented on ds-image-analysis-swagger/src/main/swagger/ds-image-analysis.yml
> +      responses:
Please provide an example of a response.

2020-01-31 13:24 UTC, tokee commented on ds-image-analysis-ws/src/main/java/dk/kb/api/webservice/ApiServiceImpl.java
> +            e.printStackTrace();
Please send an error back to the caller instead of (from the caller's perspective) silently fail.
Also please use `log.error("Description of what went wrong", e)` instead of `e.printStackTrace()`.

2020-01-31 13:24 UTC, tokee commented on ds-image-analysis-swagger/src/main/swagger/ds-image-analysis.yml
> +          description: 'Hash values divided by a ; character'
Why not use 2 parameters `hash1` and `hash2` instead of the `;`-divider thing?

2020-01-31 14:10 UTC, tokee requested changes

2020-01-31 14:10 UTC, tokee commented on ds-image-analysis-swagger/src/main/swagger/ds-image-analysis.yml
> +  - url:  /ds-pictureHash/api
Shouldn't this be `/ds-image-analysis`?

2020-01-31 14:10 UTC, tokee commented on ds-image-analysis-swagger/src/main/swagger/ds-image-analysis.yml
> +  #   http://localhost:8080/ds-image-analysis/api/imageDHash/imgPath/?imgPath=<path to the image>
Please correct `imgPath` to `imgURL`.

2020-01-31 14:10 UTC, tokee commented on ds-image-analysis-ws/src/main/java/dk/kb/api/webservice/ApiServiceImpl.java
> +    }
`algorithm` is not used for anything!?

2020-02-03 09:50 UTC, Knud-Aage commented on ds-image-analysis-ws/src/main/java/dk/kb/api/webservice/ApiServiceImpl.java
> +    private static final String filePath= "imgHash";
Changed the code to implement Files.createTempFile

2020-02-03 10:04 UTC, Knud-Aage commented on ds-image-analysis-ws/src/main/java/dk/kb/api/webservice/ApiServiceImpl.java
> +            Files.deleteIfExists(Paths.get(filePath));
I put it in the finally block, but I had to put a try clause around it because it might result in a IOException

2020-02-03 10:08 UTC, Knud-Aage commented on ds-image-analysis-ws/src/test/java/dk/kb/api/webservice/ApiServiceImplTest.java
> +        Assertions.assertEquals(true, result.contains("message: 2"));
Done

2020-02-03 10:37 UTC, Knud-Aage commented on ds-image-analysis-ws/src/main/java/dk/kb/api/webservice/ApiServiceImpl.java
> +            e.printStackTrace();
Done

2020-02-03 10:39 UTC, Knud-Aage commented on ds-image-analysis-swagger/src/main/swagger/ds-image-analysis.yml
> +          description: 'Hash values divided by a ; character'
As far as I could find out it is not currently possible to have more than one parameter. Hopefully I am wrong, because the code is quite ugly...

2020-02-03 10:41 UTC, Knud-Aage commented on ds-image-analysis-swagger/src/main/swagger/ds-image-analysis.yml
> +  #   http://localhost:8080/ds-image-analysis/api/imageDHash/imgPath/?imgPath=<path to the image>
Done

2020-02-03 10:46 UTC, Knud-Aage commented on ds-image-analysis-ws/src/main/java/dk/kb/api/webservice/ApiServiceImpl.java
> +    }
Removed

2020-02-05 12:50 UTC, tokee commented on ds-image-analysis-ws/src/main/java/dk/kb/api/webservice/ApiServiceImpl.java
> +            Files.deleteIfExists(Paths.get(filePath));
You could put it in a subsequent `try...catch`, but nesting is also fine.

2020-02-05 12:54 UTC, tokee commented on ds-image-analysis-ws/src/main/java/dk/kb/api/webservice/ApiServiceImpl.java
> +    private static final String filePath= "imgHash";
The method `getFile` changes `uniquePath`, which is later used by `Files.deleteIfExists(getUniquePath());`. If another request comes in before the delete is activated, `uniquePath` will be changed at the first file will never be deleted.

This can be solved by not storing the unique path as a field

2020-02-05 13:09 UTC, tokee commented on ds-image-analysis-swagger/src/main/swagger/ds-image-analysis.yml
> +      responses:
OpenAPI/Swagger has an explicit key for examples: https://swagger.io/docs/specification/adding-examples/ - it is better to use that than write examples in `description`.

2020-02-05 13:11 UTC, tokee commented on ds-image-analysis-swagger/src/main/swagger/ds-image-analysis.yml
> +          description: 'Hash values divided by a ; character'
Talk with halina about it: She has multi-parameter definitions in the `kb-api`-project.

2020-02-06 14:00 UTC, Knud-Aage commented on ds-image-analysis-ws/src/main/java/dk/kb/api/webservice/ApiServiceImpl.java
> +    private static final String filePath= "imgHash";
Solves it in DIGISAM-226

2020-02-06 14:01 UTC, Knud-Aage commented on ds-image-analysis-swagger/src/main/swagger/ds-image-analysis.yml
> +      responses:
I will do it in DIGISAM-226

2020-02-06 14:02 UTC, Knud-Aage commented on ds-image-analysis-swagger/src/main/swagger/ds-image-analysis.yml
> +          description: 'Hash values divided by a ; character'
I will do it in DIGISAM-226

2020-02-06 14:02 UTC, merged